# Generated by Django 5.0.4 on 2024-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_confirmemailuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmemailuser',
            name='token',
            field=models.IntegerField(),
        ),
    ]
