# Generated by Django 5.0.4 on 2024-04-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_confirmemailuser_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmemailuser',
            old_name='token',
            new_name='code',
        ),
    ]
